import { Property } from '@/types';

export const SELECT_STAY_PROPERTIES: Property[] = [
    {
        id: 'boho_breeze_1',
        title: 'Boho Breeze 1 | 1BHK Apartment in Arpora | Pool Access | Garden View Balcony | Fully Equipped Kitchen',
        location: 'Goa',
        pricePerNight: 5000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'ac', name: 'Air Conditioning', iconName: 'AirVent' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Parking', iconName: 'ParkingCircle' },
            { id: 'tv', name: 'HDTV with Amazon Prime Video, Disney+, Netflix', iconName: 'Tv2' },
            { id: 'washing_machine', name: 'Washing Machine', iconName: 'WashingMachine' },
            { id: 'first_aid_kit', name: 'First Aid Kit', iconName: 'FirstAidKit' },
            { id: 'sun_loungers', name: 'Sun Loungers', iconName: 'SunLoungers' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-19-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-1-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-13-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-3-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-4-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-14-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-15-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-2-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-8-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/ca5e21d2-ff7a-4680-8474-ffa6465b1893.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/4c3ae482-4783-4858-a881-68f66657e41c-1024x683.jpg',
        ],
        description: '1BHK apartment in Arpora with pool access, garden view balcony, and fully equipped kitchen.',
        longDescription:
            'Immerse yourself in the serene beauty of Goa with this charming 1BHK apartment, nestled amidst the verdant forests of Assagao. Wake up to the symphony of birdsongs, breathe in the fresh air, and unwind in the tranquility of your own private haven. Step inside and be greeted by a bright and airy space, adorned with local touches that reflect Goa’s unique charm.\n\nKey Features:\n- 1 bedroom with en-suite bathroom\n- Shared outdoor pool\n- Garden, mountain, and park views\n- Fully equipped kitchen\n- HDTV with Amazon Prime Video, Disney+, Netflix\n- Free WiFi, air conditioning\n- Washing machine\n- Free parking\n- First aid kit\n- Sun loungers',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 0,
        reviews: [],
        type: 'Apartment',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'boho_breeze_1',
        title: 'Boho Breeze 1 | 1BHK Apartment in Arpora | Pool Access | Garden View Balcony | Fully Equipped Kitchen',
        location: 'Goa',
        pricePerNight: 5000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'ac', name: 'Air Conditioning', iconName: 'AirVent' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Parking', iconName: 'ParkingCircle' },
            { id: 'tv', name: 'HDTV with Amazon Prime Video, Disney+, Netflix', iconName: 'Tv2' },
            { id: 'washing_machine', name: 'Washing Machine', iconName: 'WashingMachine' },
            { id: 'first_aid_kit', name: 'First Aid Kit', iconName: 'FirstAidKit' },
            { id: 'sun_loungers', name: 'Sun Loungers', iconName: 'SunLoungers' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-19-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-1-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-13-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-3-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-4-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-14-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-15-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-2-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/AsagnRsdncy-105-8-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/ca5e21d2-ff7a-4680-8474-ffa6465b1893.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/4c3ae482-4783-4858-a881-68f66657e41c-1024x683.jpg',
        ],
        description: '1BHK apartment in Arpora with pool access, garden view balcony, and fully equipped kitchen.',
        longDescription:
            'Immerse yourself in the serene beauty of Goa with this charming 1BHK apartment, nestled amidst the verdant forests of Assagao. Wake up to the symphony of birdsongs, breathe in the fresh air, and unwind in the tranquility of your own private haven. Step inside and be greeted by a bright and airy space, adorned with local touches that reflect Goa’s unique charm.\n\nKey Features:\n- 1 bedroom with en-suite bathroom\n- Shared outdoor pool\n- Garden, mountain, and park views\n- Fully equipped kitchen\n- HDTV with Amazon Prime Video, Disney+, Netflix\n- Free WiFi, air conditioning\n- Washing machine\n- Free parking\n- First aid kit\n- Sun loungers',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 0,
        reviews: [],
        type: 'Apartment',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'boho_breeze_2',
        title: 'Boho Breeze 2 | 2BHK Cozy Apartment | Sleeps 5 | AC & TV | Private Patio | Genset | Assagao',
        location: 'Goa',
        pricePerNight: 7000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'ac', name: 'Air Conditioning', iconName: 'AirVent' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Parking', iconName: 'ParkingCircle' },
            { id: 'tv', name: 'TV', iconName: 'Tv2' },
            { id: 'washing_machine', name: 'Washing Machine', iconName: 'WashingMachine' },
            { id: 'microwave', name: 'Microwave', iconName: 'Microwave' },
            { id: 'sun_loungers', name: 'Sun Loungers', iconName: 'SunLoungers' },
            { id: 'board_games', name: 'Board Games', iconName: 'BoardGames' },
            { id: 'outdoor_playground', name: 'Outdoor Playground', iconName: 'Playground' },
            { id: 'private_patio', name: 'Private Patio or Balcony', iconName: 'Patio' },
            { id: 'shared_garden', name: 'Shared Back Garden', iconName: 'Garden' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/35f0d1bb-5781-42c1-bcd4-a673f0addd7a-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/8233d452-aa8d-4ac8-832a-230f2b1adcde-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/18429e9c-7c28-4747-b9f7-aa0e316a5b35-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/1736454c-d40e-490d-8bf7-59f92850d64c-1.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/4497744e-00ac-4b4a-af62-15c3bcaef6cf-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/60420288-fe2f-4dc9-a9e8-db25820c31f1-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/acfa413d-8317-416f-8a85-1cd4a4d4d391-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/b99c1f44-a2a0-4736-b787-603dfc6ddbf6-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/b924c78c-bcfd-4cd7-9823-67894b2cc4a8-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/c0d6f80c-cf61-4d86-8bd5-2750d66ab3eb-3.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/cb035595-39ec-47f4-b50b-f29116537a9e-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/e0214ab7-dcc8-4df2-b7a0-3413eac3052e-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/0e5aee1c-c235-43c8-9769-dee71e17d797-3.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/15d3124c-f008-42fc-9df2-2da03c9e11d9-3.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/30d0cf70-c71d-40be-876f-140532caeedc-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/15d3124c-f008-42fc-9df2-2da03c9e11d9-1-1024x683.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/0e5aee1c-c235-43c8-9769-dee71e17d797-1.avif',
        ],
        description: '2BHK cozy apartment in Assagao, sleeps 5, with AC, TV, private patio, and genset.',
        longDescription:
            'Unwind in the heart of Goa’s serene beauty at our charming 2BHK apartment in Assagao. Escape the hustle and bustle while still being close to the vibrant beaches and nightlife. This fully furnished haven offers a perfect blend of comfort and tranquility, ideal for couples, families, or friends seeking a memorable Goan getaway.\n\nKey Features:\n- 2 bedrooms with en-suite bathrooms\n- Shared outdoor pool\n- Private patio or balcony\n- Fully equipped kitchen with microwave\n- TV, free WiFi, air conditioning\n- Washing machine\n- Free parking\n- Outdoor playground and board games\n- Shared back garden\n- Genset for uninterrupted power',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 0,
        reviews: [],
        type: 'Apartment',
        guests: 5,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'captains_quarters',
        title: 'Captains Quarters | 2BHK Pool-Facing Apartment with Large Balconies, AC, Full Kitchen & Palm Views',
        location: 'Goa',
        pricePerNight: 7000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'ac', name: 'Air Conditioning', iconName: 'AirVent' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Residential Garage', iconName: 'ParkingCircle' },
            { id: 'tv', name: '60-inch HDTV', iconName: 'Tv2' },
            { id: 'sauna', name: 'Shared Sauna', iconName: 'Sauna' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
            { id: 'security_cameras', name: 'Exterior Security Cameras', iconName: 'SecurityCamera' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/a35d3ec9-e920-4e3a-9aec-523c782006d0.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/1db930e0-66e0-4df5-90bb-dc8f5c55be9d-1.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/773a7a1d-0b6c-44bd-98dc-2751dcaafc4a.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/7b8d539b-a773-4c56-9ceb-1badf9f2b54f-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/4a1b3957-f9b9-4f71-b578-71e4ccfff1b5.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/b1e307df-26f8-4f2b-becb-390d775e783a.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/d180f575-ae02-4249-910c-00a5f3c35ade.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/94be4411-5d3d-4cb9-bc53-c42ab090ce28-2.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/d59c497e-5023-4dac-a2a9-412fd105b373.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/0735b6bc-4ce2-436a-b6f2-c19ca4c0f0c7.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/396f8d91-3f00-4b39-b471-8b5f4bd06866.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/ceedbdfe-c906-4025-9637-3bd117e6da27-1.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/b546b163-4646-4df0-9afe-2bd1ea4ce284.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/7b8d539b-a773-4c56-9ceb-1badf9f2b54f-1-1024x683.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/13-3-1024x379.jpg',
        ],
        description: '2BHK pool-facing apartment with large balconies, AC, full kitchen, and palm views near Baga Beach.',
        longDescription:
            'Embrace the nautical spirit at Captain’s Quarters, a charming 2-bedroom apartment boasting stunning views of the pool and lush paddy fields, just moments from the vibrant Baga Beach. This thoughtfully designed space blends coastal charm with modern comforts, offering a perfect haven for families and friends seeking a memorable Goa getaway. Two minute walk to Baga – Calangute beach road including the famous Titos lane. Centrally located: Anjuna, Vagator, Assagao all are just a 15 min drive. Get food or grocery deliveries from any of the best restaurants in Goa in only 10-15 mins using Swiggy, Zomato or Blinkit.\n\nKey Features:\n- 2 bedrooms with en-suite bathrooms\n- Shared outdoor pool and sauna\n- Large balconies with pool and palm views\n- Fully equipped kitchen\n- 60-inch HDTV\n- Free WiFi, air conditioning\n- Free residential garage\n- Dedicated workspace\n- Exterior security cameras',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Aslam',
                comment:
                    'We Booked these place for our Sons first Birthday. We Enjoyed a lot. The flat is well decorated and interior design is awesome. Flat comes in private society and have full amenities like pool, Gym, Garden. Good Experience.',
                rating: 5,
            },
        ],
        type: 'Apartment',
        guests: 0,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'coastal_calm',
        title: 'Coastal Calm | 1BHK Resort-Style Stay | Pool | Jacuzzi | Gym | Sauna | Indoor Games | Parking',
        location: 'Goa',
        pricePerNight: 5000,
        amenities: [
            { id: 'wifi', name: 'Fast WiFi – 93 Mbps', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Parking on Premises', iconName: 'ParkingCircle' },
            { id: 'sauna', name: 'Shared Sauna', iconName: 'Sauna' },
            { id: 'jacuzzi', name: 'Jacuzzi', iconName: 'Jacuzzi' },
            { id: 'gym', name: 'Gym', iconName: 'Gym' },
            { id: 'indoor_games', name: 'Indoor Games', iconName: 'IndoorGames' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-1UG4-SG-1-27-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-1UG4-SG-1-4-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-1UG4-SG-1-15-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-23.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-25.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-33.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-1.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-8.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-10.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-12.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-14.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-1UG4-SG-1-20.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/2a6ed9e1-7669-46a2-9215-e512e541df3d-1-1024x621.jpg',
        ],
        description: '1BHK resort-style stay with pool, jacuzzi, gym, sauna, indoor games, and parking near Baga Beach.',
        longDescription:
            'Relax, unwind and enjoy the Goa life at our home. Located in a peaceful neighbourhood in the otherwise bustling Baga Beach area, our home opens into a private sit out area facing a huge green lawn. With all modern-day amenities, the flat is perfect for a couple or a family with 2 kids planning to holiday in Goa. You will have free access to 2 pools, jacuzzi, gym, steam & sauna room, indoor games and parking.\n\nKey Features:\n- 1 bedroom with en-suite bathroom\n- Two shared outdoor pools\n- Jacuzzi, gym, and sauna\n- Indoor games\n- Fast WiFi (93 Mbps)\n- Fully equipped kitchen\n- Free parking\n- Dedicated workspace\n- Garden and park views',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Nitin Kant',
                comment:
                    'Stay was very comfortable and inside a gated society. All the amenities were as per description. The location is great, near to all major attractions. Highly recommend.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Abhinav',
                comment:
                    'I had a wonderful stay at this property. The space was exactly as described and the location was ideal, making it convenient for exploring the area. I would surely recommend this Airbnb and look forward to returning in the future!',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Sheila',
                comment:
                    'We had a wonderful stay!!! We were wanting to stay longer but it was booked so we had to move and try somewhere else which is fine!! I would completely recommend this place to anyone and would love to come back again one day!!',
                rating: 5,
            },
        ],
        type: 'Apartment',
        guests: 4,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'lagoon_nest',
        title: 'Lagoon Nest | 2BHK Apartment | Baga Beach | Pool | High-Speed WiFi | Sauna | Private Parking',
        location: 'Goa',
        pricePerNight: 7000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Carport on Premises', iconName: 'ParkingCircle' },
            { id: 'sauna', name: 'Shared Sauna', iconName: 'Sauna' },
            { id: 'tv', name: 'HDTV with Amazon Prime Video, Apple TV, Chromecast, Disney+, Netflix', iconName: 'Tv2' },
            { id: 'gym', name: 'Shared Gym in Building', iconName: 'Gym' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
            { id: 'lift', name: 'Lift', iconName: 'Lift' },
            { id: 'ev_charger', name: 'EV Charger', iconName: 'EVCharger' },
            { id: 'single_level', name: 'Single Level Home', iconName: 'SingleLevel' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-63-e1742875019894.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-67-e1742875035631.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-89-e1742875048942.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-31-e1742874862834.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-3-e1742874899993.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-13-e1742874928532.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-32-e1742874954172.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-42-e1742874991721.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-5UG2-S_G-Sml-50.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/0d531e60-214b-4a2e-a098-c0195e162ee4-1-1024x612.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/23ab55ab-834e-431a-961b-654a4fad1586-1024x654.jpeg',
        ],
        description: '2BHK apartment near Baga Beach with pool, high-speed WiFi, sauna, and private parking.',
        longDescription:
            'Welcome to our home that is curated with all our love, for you to feel the serenity and luxury that we experience too. Nestled in a quaint ‘Waddo’ in the otherwise hustling party beach area in North Goa, our apartment fills all its rooms with natural light and cool sea winds that open up into a refreshing green expanse. Make yourself feel at home in the large living room with a fully equipped kitchen, the two earthy yet vibrant bedrooms with attached baths and a large-private sit out space.\n\nKey Features:\n- 2 bedrooms with en-suite bathrooms\n- Shared outdoor pool and sauna\n- Fully equipped kitchen\n- HDTV with Amazon Prime Video, Apple TV, Chromecast, Disney+, Netflix\n- High-speed WiFi\n- Free carport parking\n- Shared gym in building\n- Lift and EV charger\n- Single level home with park view',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 0,
        reviews: [],
        type: 'Apartment',
        guests: 0,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'monsoon_escape',
        title: 'Monsoon Escape | 1BHK Luxe Stay in North Goa with Pool, Gym, Back Garden & Free Guest Access',
        location: 'Goa',
        pricePerNight: 5000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'tv', name: 'HDTV with Amazon Prime Video, Disney+, Netflix', iconName: 'Tv2' },
            { id: 'gym', name: 'Shared Gym', iconName: 'Gym' },
            { id: 'sauna', name: 'Shared Sauna', iconName: 'Sauna' },
            { id: 'washer', name: 'Free Washer – In Unit', iconName: 'WashingMachine' },
            { id: 'first_aid_kit', name: 'First Aid Kit', iconName: 'FirstAidKit' },
            { id: 'sun_loungers', name: 'Sun Loungers', iconName: 'SunLoungers' },
            { id: 'pool_table', name: 'Pool Table', iconName: 'PoolTable' },
            { id: 'back_garden', name: 'Shared Back Garden', iconName: 'Garden' },
            { id: 'ac', name: 'Air Conditioning', iconName: 'AirVent' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1269-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1293-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1321-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1322-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1205-scaled.jpeg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1244-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1260-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1193-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1195-scaled.jpeg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1226-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1231-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1259-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1218-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1178-scaled.jpeg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1210-scaled.jpeg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1232-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1236-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1254-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/2ad46ec0-a9f6-4b1e-a082-fe70b4f0da05-2-1024x768.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/97ebace4-4a83-47b1-9317-56812470ded4-1024x684.jpeg',
        ],
        description: '1BHK luxe stay in North Goa with pool, gym, back garden, and free guest access near Baga Beach.',
        longDescription:
            'Located in the heart of North Goa’s party district, this luxurious apartment is perfect for a laid-back yet upscale stay. Just a 2-minute walk from the bustling Baga-Calangute beach road and the iconic Titos Lane, it offers unmatched convenience. Anjuna, Vagator, and Assagao are all within a 15-minute drive, making it easy to explore Goa’s vibrant hotspots. Fully equipped with best-in-class amenities, the space is designed for relaxation while embracing the true Goa vibe. Plus, with Swiggy, Zomato, and Blinkit, you can get food and groceries delivered in just 10-15 minutes, ensuring a seamless and stress-free getaway.\n\nKey Features:\n- 1 bedroom with en-suite bathroom\n- Shared outdoor pool and sauna\n- Shared gym and pool table\n- Fully equipped kitchen\n- HDTV with Amazon Prime Video, Disney+, Netflix\n- Free WiFi and air conditioning\n- Free washer in unit\n- Shared back garden and sun loungers\n- First aid kit',
        hostName: 'Gaurav',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Shiva',
                comment: 'everything was so good and went well already missing the place',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Vineet',
                comment:
                    'I was initially a bit nervous about booking this property since it was new and had no reviews, especially as it was a trip with my family. However, it turned out to be an absolutely amazing experience! Gaurav was an exceptional host, and the house was exactly as it appeared in the photos—no surprises',
                rating: 5,
            },
        ],
        type: 'Apartment',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'noir_pop',
        title: 'Noir Pop | 1BHK Modern Apartment | Near Baga Beach | Balcony | Kitchenette | Pool | Aesthetic Interiors',
        location: 'Goa',
        pricePerNight: 5000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Carport on Premises', iconName: 'ParkingCircle' },
            { id: 'sauna', name: 'Shared Sauna', iconName: 'Sauna' },
            { id: 'tv', name: '50-inch HDTV with Netflix, Apple TV, Amazon Prime Video, Disney+', iconName: 'Tv2' },
            { id: 'lift', name: 'Lift', iconName: 'Lift' },
            { id: 'ev_charger', name: 'EV Charger – Level 1', iconName: 'EVCharger' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0718-scaled.jpeg',
            'https://selectstays.in/wp-content/uploads/2025/3/IMG_0896-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0750-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0734-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0779-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0673-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0709-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0900-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0915-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0784-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0653-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_0722-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/5d581f52-2e77-4980-97e1-8bbb105bc077.avif',
        ],
        description: '1BHK modern apartment near Baga Beach with balcony, kitchenette, pool, and aesthetic interiors.',
        longDescription:
            'This luxurious apartment is perfectly located in the heart of North Goa’s party district, just a 2-minute walk from the vibrant Baga-Calangute beach road and the famous Tito’s Lane. Designed for a chilled-out stay, it offers best-in-class amenities that bring together the perfect blend of comfort and the true Goa vibe. Whether you’re looking to explore hotspots like Anjuna, Vagator, and Assagao—just a 15-minute drive away—or enjoy the convenience of quick food and grocery deliveries from top restaurants via Swiggy, Zomato, or Blinkit, this stay ensures you experience Goa at its finest.\n\nKey Features:\n- 1 bedroom with en-suite bathroom\n- Shared outdoor pool and sauna\n- Fully equipped kitchenette\n- 50-inch HDTV with Netflix, Apple TV, Amazon Prime Video, Disney+\n- Free WiFi\n- Free carport parking\n- Lift and EV charger (Level 1)\n- Balcony with aesthetic interiors',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Jihye',
                comment:
                    'It was a place where you could relax during a trip that was well-equipped, neatly organized, and exhausted. Two cleaners visited every day to ask about the cleaning doctor and took care of the shortcomings, so I felt like it was a well-maintained house. It was also convenient to use the shared sauna poo',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Rahul',
                comment:
                    'A flat in well maintained gated community. Cleanliness maintained as described. Everyday room cleaning was very helpful for me, as i was with 2 little kids. Host and caretaker are responsive and helpful. Dedicated parking for each flats. Clean pool and Gym with strict costume rules. Not much far from Tito’s lane and nearby shopping arras a',
                rating: 5,
            },
        ],
        type: 'Apartment',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'soulful_shores',
        title: 'Soulful Shores | 2BHK Work-Friendly Apartment Near Baga Beach with High-Speed WiFi & Two Private Balconies',
        location: 'Goa',
        pricePerNight: 7000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Carport on Premises', iconName: 'ParkingCircle' },
            { id: 'sauna', name: 'Shared Sauna', iconName: 'Sauna' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-11-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-17-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-31-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-33-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-28-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-4-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-29-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-1-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-6-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-20-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-24-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-10-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-19-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-6T3-SG-40.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/57295e10-eedf-4237-b92b-aff5f2b8b6ae.avif',
            'https://selectstays.in/wp-content/uploads/2025/03/c71306fd-3121-4821-ad1b-593599cb5727.avif',
        ],
        description: '2BHK work-friendly apartment near Baga Beach with high-speed WiFi and two private balconies.',
        longDescription:
            'Welcome to our home, for you to feel the serenity and luxury that we experience too. Nestled in a quaint ‘Waddo’ in the otherwise hustling party beach area in North Goa, our apartment fills all its rooms with natural light and cool sea winds that open up into a refreshing and airy huge balcony. Make yourself feel at home in the large living room with a fully equipped kitchen, the two earthy yet vibrant bedrooms with attached ensuite baths and private balconies.\n\nKey Features:\n- 2 bedrooms with en-suite bathrooms\n- Shared outdoor pool and sauna\n- Fully equipped kitchen\n- High-speed WiFi\n- Free carport parking\n- Dedicated workspace\n- Garden and park views\n- Two private balconies',
        hostName: 'Gaurav',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Seema',
                comment:
                    'We had a good stay. The place was neat and clean. The host and the caretaker were helpful. Definitely coming back here again.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Sanjit',
                comment: 'Great peaceful place very close to Baga. Good place if you are planning to stay for a week or longer',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Daigan',
                comment:
                    'Gaurav was attentive and helpful during our stay. Cleaning was regular and the location is well situated within Goa.',
                rating: 5,
            },
        ],
        type: 'Apartment',
        guests: 0,
        bedrooms: 2,
        beds: 2,
        baths: 2,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'breezehaus',
        title: 'BreezeHaus | 1 Bedroom Studio at Baga Beach with WiFi, AC, Kitchenette, Pool Access and Parking',
        location: 'Goa',
        pricePerNight: 3000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'ac', name: 'Air Conditioning', iconName: 'AirVent' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchenette', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Carport on Premises', iconName: 'ParkingCircle' },
            { id: 'tv', name: 'HDTV with Amazon Prime Video, Disney+, Netflix', iconName: 'Tv2' },
            { id: 'sauna', name: 'Sauna', iconName: 'Sauna' },
            { id: 'jacuzzi', name: 'Jacuzzi', iconName: 'Jacuzzi' },
            { id: 'gym', name: 'Gym', iconName: 'Gym' },
            { id: 'spa', name: 'Spa', iconName: 'Spa' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
            { id: 'lift', name: 'Lift', iconName: 'Lift' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/05/DSC_2940-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC_3039-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC_3054-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_2873-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_2880-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_2895-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_2908-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_3003-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_3045-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_2839-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC_3086-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC_2999-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC_2900-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC_2929-Edit-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/c7f6cc90-9790-4039-bd6f-b634b5efb31d-1.avif',
        ],
        description: '1-bedroom studio near Baga Beach with WiFi, AC, kitchenette, pool access, and parking.',
        longDescription:
            'A charming, stylish, and comfortable studio apartment in a peaceful gated complex, less than a kilometer from Baga Beach. Enjoy ample sunshine and lush green views from the cozy balcony. Perfect for a couple or a small family, the apartment is fitted with modern amenities, including high-speed 300 Mbps Wi-Fi and a fully equipped kitchenette. Guests get free access to 5-star facilities like two pools, a jacuzzi, a gym, a spa, and more. Centrally located near Baga and Calangute beaches, yet tucked away in a quiet lane, it offers the best of both worlds—serenity and easy access to Goa’s vibrant nightlife and dining spots.\n\nKey Features:\n- 1 bedroom studio with en-suite bathroom\n- Two shared outdoor pools\n- Jacuzzi, gym, sauna, and spa\n- Fully equipped kitchenette\n- HDTV with Amazon Prime Video, Disney+, Netflix\n- High-speed 300 Mbps WiFi\n- Free carport parking\n- Dedicated workspace\n- Lift and cozy balcony',
        hostName: 'Sapan',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Gowsal Hudda',
                comment:
                    'The place was exactly same as shown in pictures. Care taker Sapan was always available when needed. The quality of items provided are really good . I hope he maintain this standard. Very comfortable for families. you have many restaurants nearby .',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Saket',
                comment:
                    'A very reasonable studio apartment in a very nice gated community, walking distance from Baga and Calangute. Some initial hiccups but the host fixed them immediately. A few suggestions,, extra towels would be nice and maybe some storage space',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Amar',
                comment:
                    'A great place to stay. Rooms were nice and clean as expected and shown in the pictures. This place is close to all the main places in north goa. Caretaker sapan was very helpful. Would definitely recommend and stay again.',
                rating: 5,
            },
        ],
        type: 'Studio',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'honeycomb',
        title: 'Honeycomb | Fully Equipped Holiday Studio | Candolim Beach | WiFi | Pool | Kitchenette',
        location: 'Goa',
        pricePerNight: 2500,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchenette', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Parking on Premises', iconName: 'ParkingCircle' },
            { id: 'tv', name: '30-inch HDTV', iconName: 'Tv2' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-8-scaled-e1742880692601.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-13-scaled-e1742880709612.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-15-scaled-e1742880728905.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-14-e1742880645912.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-12-scaled-e1742880667617.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-17-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/ebc5d1ee-0573-4a41-9f4f-cd9f56fbe949-1024x631.jpeg',
        ],
        description: 'Fully equipped holiday studio near Candolim Beach with WiFi, pool, and kitchenette.',
        longDescription:
            'Enjoy easy access to everything from this perfectly located comfortable home base. The apartment is part of a gated apartment complex which has access from both Candolim beach road and Nerul-Candolim Road. Candolim beach is just about a km away. The apartment is at the end of a clean and peaceful lane connecting into the bustling Candolim-Calungute road in North Goa.\n\nKey Features:\n- 1 bedroom studio with en-suite bathroom\n- Shared outdoor pool\n- Fully equipped kitchenette\n- 30-inch HDTV\n- Free WiFi\n- Free parking on premises\n- Dedicated workspace\n- Garden and park views',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Akansha',
                comment:
                    'Gaurav have been a great host. I loved the property and the location is easy to locate. Gaurav has got good care taker as well, they very easy to communicate to and was very helpful. Highly recommended as the property is budget friendly as well.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Rekha',
                comment:
                    'The place was very comfortable, a home away from home. We enjoyed our stay to the fullest extent, Bijan was very welcoming and helpful, my husband felt tired & unwell on our last evening, Bijan quickly sent us a cab to the hospital, we thank him for that.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Amit',
                comment:
                    'Great place to stay. Felt Home away from Home 🏡. Exactly same as photos listed. Sushant was great caretaker, was a phone call away for any help. He managed cake for me at night as it was my wife’s birthday. Thank you so much for making our stay and everything memorable.',
                rating: 5,
            },
        ],
        type: 'Studio',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'little_palm',
        title: 'Little Palm | Baga Beachfront Studio Garden View | Pool Access | Private Parking',
        location: 'Goa',
        pricePerNight: 3000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'ac', name: 'AC – split-type ductless system', iconName: 'AirVent' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Residential Garage on Premises', iconName: 'ParkingCircle' },
            { id: 'tv', name: 'HDTV with Amazon Prime Video, Disney+, Netflix', iconName: 'Tv2' },
            { id: 'washer', name: 'Free Washer – In Unit', iconName: 'WashingMachine' },
            { id: 'first_aid_kit', name: 'First Aid Kit', iconName: 'FirstAidKit' },
            { id: 'private_entrance', name: 'Private Entrance', iconName: 'PrivateEntrance' },
            { id: 'outdoor_dining', name: 'Outdoor Dining Area', iconName: 'OutdoorDining' },
            { id: 'beach_access', name: 'Beach Access – Beachfront', iconName: 'BeachAccess' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1099-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1101-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1102-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1080-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1119-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1141-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1118-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1092-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/IMG_1094-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1103-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1117-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1120-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1128-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1133-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1137-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1139-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1140-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1095-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/IMG_1098-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/fb8e9242-74f8-4332-8e08-f3bf5a3a8bc2.avif',
        ],
        description: 'Beachfront studio near Baga Beach with garden view, pool access, and private parking.',
        longDescription:
            'Breath in fresh air at this spacious and comfortable studio near Baga Beach. Peaceful, stylish and comfortable studio apartment with views of lush green Goa. Located less than a Km from Baga & Calangute beach’s in a peaceful neighbourhood. Feel the cool sea breeze all day long with ample sunshine as you start your mornings with lush green views straight from your window. Fitted with all modern-day amenities this studio apartment is perfect for a couple or a family of three.\n\nKey Features:\n- 1 bedroom studio with en-suite bathroom\n- Shared outdoor pool\n- Fully equipped kitchen\n- HDTV with Amazon Prime Video, Disney+, Netflix\n- Free WiFi and AC\n- Free residential garage\n- Free washer in unit\n- Private entrance and outdoor dining area\n- First aid kit\n- Beachfront access with garden view',
        hostName: 'Gaurav',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Nikhil',
                comment:
                    'The stay was cozy and great. Baga beach and Calangute are at walkable distance. Thank you Gaurav for the super place',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Vipin',
                comment:
                    'Great place to stay. I’ve been here twice and loved the stay. It’s private and very well connected to the beach. Amenities like pool, gym, parking are available. Will definitely recommend this one whoever is looking to get a place in north Goa.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Sameeksha',
                comment:
                    'I had a fantastic experience staying at this place! They ensure we had everything we needed. The home was clean, cozy, and exactly as described in the listing. I highly recommend staying here and would love to return in the future.',
                rating: 5,
            },
        ],
        type: 'Studio',
        guests: 3,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'palm_views',
        title: 'Palm Views | Furnished Studio Apartment Near Baga Beach with Workspace, WiFi & Pool Access',
        location: 'Goa',
        pricePerNight: 3000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchenette', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Residential Garage on Premises', iconName: 'ParkingCircle' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
            { id: 'beach_access', name: 'Shared Beach Access', iconName: 'BeachAccess' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-2T1-SG-16-1-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-2T1-SG-18-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-2T1-SG-19-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-20.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-1.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-2.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-3.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-17.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-4.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-9.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-14.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-16.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-SeaWinds-2T1-SG-22.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-2T1-SG-11-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/Acron-SeaWinds-2T1-SG-15-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/7b57cdf2-ec2c-4460-9119-0a0eb5bff088-1-1024x706.jpg',
        ],
        description: 'Furnished studio apartment near Baga Beach with workspace, WiFi, and pool access.',
        longDescription:
            'Scenic, stylish and comfortable studio apartment with views of lush green Goa. Located less than a Km from Baga beach in a peaceful neighbourhood. Feel the cool sea breeze all day long with ample sunshine as you start your mornings with lush green views in the cozy comfortable balcony. Fitted with all modern-day amenities the studio apartment is perfect for a couple or a family of three. The apartment is at the end of a clean and peaceful lane in the otherwise bustling party beach area of North Goa.\n\nKey Features:\n- 1 bedroom studio with en-suite bathroom\n- Shared outdoor pool\n- Fully equipped kitchenette\n- Free WiFi\n- Free residential garage\n- Dedicated workspace\n- Park and garden views\n- Shared beach access',
        hostName: 'Gaurav',
        hostAvatarUrl: '',
        rating: 4.7,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Aditya',
                comment:
                    'Fantastic Stay Near Baga Beach with Outstanding Host Support! We had an amazing stay at this apartment near Baga Beach. The location was perfect—just a short walk to the vibrant Baga beach, yet tucked away enough to enjoy peace and quiet. The apartment itself was clean, well-maintained, and equipped with all the amenities I',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Shubham',
                comment:
                    'Gaurav’s place was great, I found the apartment exactly as per description, with all modern day amenities in place for a comfortable, relaxing and peaceful stay. What stood out for me was dedicated 4 wheeler parking, helpful and always responsive caretaker Sapan, RO water availability round the clock, and a fast Internet connection (speed approx',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Ashima',
                comment:
                    'Gaurav was helpful and communicated well and was considerate, allowed early check-in for my parents but the caretaker didn’t attend calls (Would take the call after calling 5 times). The taxi arranged by him for the drop to airport was of poor quality. Location was good, Instructions shared by Gaurav were very clea',
                rating: 4,
            },
        ],
        type: 'Studio',
        guests: 3,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'saffo',
        title: 'Saffo | 1RK/Studio with Mountain Views, Pool, Spacious Balcony & High-Speed WiFi Near Calangute Beach',
        location: 'Goa',
        pricePerNight: 3000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchenette', iconName: 'CookingPot' },
            { id: 'parking', name: 'Free Parking on Premises', iconName: 'ParkingCircle' },
            { id: 'sauna', name: 'Shared Sauna', iconName: 'Sauna' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-23-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-24-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-1-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-3-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-15-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-18-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-25-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-26-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Acron-Seawinds-2T8-S_G-22-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/2cde5276-8f11-41b2-b21b-2a04c96ba7c2.avif',
        ],
        description: '1RK studio with mountain views, pool, spacious balcony, and high-speed WiFi near Calangute Beach.',
        longDescription:
            'Unwind-Relax-Immerse yourself in Goa. Thats what this studio apartment offers. Located in a new, modern and centrally located complex, this home checks all its boxes to make your holiday or workaction memorable. To make your stay comfortable the apartment offers the best of amenities that you may need during your visit. This 400 soft space comes with a kitchenette, ensuite bathroom and a spacious balcony with a lounger. Amazing views of paddy fiends, lush green hills and the pool underneath. The apartment is at the end of a clean and peaceful lane in the otherwise bustling party beach area of North Goa.\n\nKey Features:\n- 1RK studio with en-suite bathroom\n- Shared outdoor pool and sauna\n- Fully equipped kitchenette\n- High-speed WiFi\n- Free parking on premises\n- Dedicated workspace\n- Garden and mountain views\n- Spacious balcony with lounger',
        hostName: 'Gaurav',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Bob',
                comment: 'Very clean and well run rental, the two swimming pools, sauna and steam room are a bonus.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Anubhav',
                comment: 'The place is neat and cozy. It’s somewhere around 1.5-2 kms away from Baga but around main places of the north.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Sambasivarao',
                comment:
                    'it’s a combination of Peaceful Apartment, Good Eminities, and at a Excellent location. Gauran and Sapan very proactive, and helpful. will visit again',
                rating: 5,
            },
        ],
        type: 'Studio',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'sundew_studio',
        title: 'Sundew Studio | 1RK Cozy Stay | Near Candolim Beach with Pool, Lift, High-Speed WiFi',
        location: 'Goa',
        pricePerNight: 2500,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'pool', name: 'Shared Outdoor Pool', iconName: 'Waves' },
            { id: 'parking', name: 'Free Parking on Premises', iconName: 'ParkingCircle' },
            { id: 'tv', name: '40-inch HDTV with Netflix, Amazon Prime Video, Fire TV', iconName: 'Tv2' },
            { id: 'ac', name: 'AC – split-type ductless system', iconName: 'AirVent' },
            { id: 'lift', name: 'Lift', iconName: 'Lift' },
            { id: 'workspace', name: 'Dedicated Workspace', iconName: 'Workspace' },
            { id: 'patio', name: 'Private Patio or Balcony', iconName: 'Patio' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-23-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-26-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-27-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-29-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-38-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/Sun_Sand-E109-21-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/2984f70e-03fd-4d5f-b569-f5ac9ebc8a09-1024x683.jpg',
        ],
        description: '1RK cozy studio near Candolim Beach with pool, lift, and high-speed WiFi.',
        longDescription:
            'Centrally located, well furnished, comfortable studio apartment unit. The apartment is part of a gated complex which has easy access from both Candolim beach and Nerul-Candolim Road. Less than a km from Candolim beach. Just 300 meters from the famous Candolim beach market. This classy looking studio apartment check all boxes to be a comfortable home for your holidays in Goa. Nested within a gated complex in the heart of Candolim Beach area this apartment comes with all modern amenities that you need after a long day of partying in Goa.\n\nKey Features:\n- 1RK studio with en-suite bathroom\n- Shared outdoor pool\n- 40-inch HDTV with Netflix, Amazon Prime Video, Fire TV\n- High-speed WiFi\n- Free parking on premises\n- Air conditioning\n- Lift\n- Dedicated workspace\n- Private patio or balcony',
        hostName: 'Gaurav',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Coco',
                comment:
                    'My stay at Gaurav´s place was delightful overall. The apartment was cozy and well-appointed, providing a comfortable retreat after a day of exploring the city.',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Deeksha',
                comment:
                    'Neat and clean property. Amazing location. Property matches pictures. Staff is responsive and helpful. It gave us a good vibe overall 😊',
                rating: 5,
            },
            {
                date: '2025-04-14',
                guestName: 'Kevin',
                comment:
                    'A very nice place at a great location. The flat was a little bit small for 2 but overall a very nice flat. The host was very kind.',
                rating: 5,
            },
        ],
        type: 'Studio',
        guests: 0,
        bedrooms: 1,
        beds: 1,
        baths: 1,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
    {
        id: 'villa_orla',
        title: 'Villa Orla | 6 Beds | Private Pool Villa with Chef & Lift Near Calangute & Anjuna',
        location: 'Goa',
        pricePerNight: 40000,
        amenities: [
            { id: 'wifi', name: 'WiFi', iconName: 'Wifi' },
            { id: 'ac', name: 'AC – split-type ductless system', iconName: 'AirVent' },
            { id: 'pool', name: 'Private Pool', iconName: 'Waves' },
            { id: 'kitchen', name: 'Kitchen', iconName: 'CookingPot' },
            { id: 'parking', name: 'Private Parking', iconName: 'ParkingCircle' },
            { id: 'tv', name: 'HDTV with Amazon Prime Video, Disney+, Netflix', iconName: 'Tv2' },
            { id: 'washer', name: 'Free Washer – In Unit', iconName: 'WashingMachine' },
            { id: 'first_aid_kit', name: 'First Aid Kit', iconName: 'FirstAidKit' },
            { id: 'hot_tub', name: 'Private Hot Tub', iconName: 'HotTub' },
            { id: 'gym', name: 'Shared Gym', iconName: 'Gym' },
            { id: 'patio', name: 'Patio', iconName: 'Patio' },
            { id: 'garden', name: 'Private Back Garden', iconName: 'Garden' },
            { id: 'waterfront', name: 'Waterfront Lake Access', iconName: 'Waterfront' },
        ],
        images: [
            'https://selectstays.in/wp-content/uploads/2025/05/DSC03540-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC03525-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC04010-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03183-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03941-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03307-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03384-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03413-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03511-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03531-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03735-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03799-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03438-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03107-HDR-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/DSC03045-scaled.jpg',
            'https://selectstays.in/wp-content/uploads/2025/03/686e7bc2-d28f-4e7c-820f-10bc38ed3f67-1-1.avif',
            'https://selectstays.in/wp-content/uploads/2025/05/DSC03326-HDR-Edit-scaled.jpg',
        ],
        description: '6-bedroom private pool villa with chef and lift near Calangute and Anjuna.',
        longDescription:
            'Experience true Luxury at our contemporary, spacious, 4 bedroom villa with personal chef, private pool, private parking and amazing amenities that too right in the heart of North Goa. Located in a gated villa complex with five-star amenities, this property in Arpora offers the perfect blend of luxury and convenience. Just five minutes from the Calangute-Anjuna main road, it provides easy access to Goa’s most popular destinations—Anjuna, Vagator, and Assagao are all within a 15-minute drive. Whether you’re craving a gourmet meal or need groceries, top restaurants and stores deliver straight to your doorstep in just 10-15 minutes via Swiggy, Zomato, or Blinkit.\n\nKey Features:\n- 6 spacious bedrooms with en-suite bathrooms\n- Private swimming pool\n- In-house chef for all meals\n- Lift for easy access\n- Fully equipped kitchen\n- Free WiFi, HDTV with Amazon Prime Video, Disney+, Netflix\n- Private parking\n- Private hot tub and shared gym\n- Private back garden and waterfront lake access\n- Patio and first aid kit',
        hostName: 'John Doe',
        hostAvatarUrl: '',
        rating: 5.0,
        reviews: [
            {
                date: '2025-04-14',
                guestName: 'Sakshi',
                comment:
                    'An absolute gem in North Goa! Villa Orla exceeded all our expectations. From the luxurious interiors to the private pool and in-house chef, everything was top-notch. The villa was spacious, spotless, and beautifully designed, making it perfect for a group stay.',
                rating: 5,
            },
        ],
        type: 'Villa',
        guests: 0,
        bedrooms: 6,
        beds: 6,
        baths: 6,
        coordinates: { lat: 15.5467, lng: 73.7518 },
    },
];
